import type { Step } from 'react-joyride';

interface TutorialStepsOptions {
  hasGoals: boolean;
}

export const getTutorialSteps = ({ hasGoals }: TutorialStepsOptions): Step[] => {
  const steps: Step[] = [
    {
      target: 'body',
      title: 'Bienvenido a tu Refugio Mental',
      content: 'Estás a punto de descubrir cómo liberar el 80% de tu carga mental. Esta no es una app de tareas común; es tu copiloto para recuperar tu tiempo.\n\n¿Hacemos el recorrido?',
      placement: 'center',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#global-add-task-button',
      title: 'Crea tu primera tarea',
      content: 'Cada vez que una idea cruce tu mente, pulsa este botón "+" para sacarla de tu cabeza.\n\nTienes dos opciones al abrirlo:\nTexto: para escribir tu tarea.\nVoz: para dictarla en movimiento.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#task-title-input',
      title: 'Escribe tu tarea',
      content: 'Es tu momento. Escribe aquí lo que necesitas hacer.\n\nSé claro y directo. Por ejemplo:\n"Estudiar capítulo 3 de matemáticas".',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#task-description-input',
      title: 'Descripción opcional',
      content: '¿Necesitas recordar detalles importantes? Escríbelos aquí.\n\nNo confíes en tu memoria. Deja que Adonai guarde los detalles por ti.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#task-link-input',
      title: 'Tu fuente de poder',
      content: 'Aquí está el truco de los que ejecutan sin excusas.\n\n¿Tienes un video de YouTube, un documento o un curso? Pégalo aquí. Cuando llegue el momento de actuar, todo estará en un solo lugar.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#task-edit-pencil',
      title: 'Edición rápida',
      content: '¿Te equivocaste al escribir el título o los detalles? Este lápiz te permite volver atrás en cualquier momento para corregir lo que necesites sin perder tu progreso.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#task-date-selector',
      title: 'La regla de oro: ponle fecha',
      content: 'Este es el paso más importante.\n\nUna tarea sin fecha es solo un deseo. Poner una fecha límite aumenta mucho la probabilidad de cumplirla.\n\nTu cerebro necesita una línea de meta para activarse.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: false,
    },
    ...(hasGoals ? [{
      target: '#task-goal-selector',
      title: 'Conecta con tus metas',
      content: 'Aquí puedes asignar esta tarea a una de tus metas.\n\nSi lo que haces no está conectado con tus metas, podrías estar haciendo trabajo basura.\n\nCada tarea asignada a una meta te acerca a lo que realmente quieres lograr.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: false,
    } as Step] : []),
    {
      target: '#task-matrix-selector',
      title: 'El secreto de la prioridad',
      content: 'Usa esta matriz para decidir qué merece tu atención.\n\n1. Importante + urgente: hazlo ya.\n2. Solo urgente: hazlo o pide ayuda.\n3. Solo importante: planifícalo.\n4. Ninguno: baja prioridad.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#task-save-btn',
      title: 'Guarda tu primera tarea',
      content: 'Has creado tu primera tarea como un profesional.\n\nGuárdala ahora para sentir la paz mental de tener el control de tu día.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
    },
    {
      target: '#mini-window-btn',
      title: 'Captura desde cualquier lugar',
      content: 'Tu productividad no se detiene. Abre la mini ventana para capturar ideas mientras navegas en otras apps, sin perder el enfoque.',
      placement: 'bottom',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#nav-week',
      title: 'Tu semana completa',
      content: 'Haz clic aquí para ver toda tu semana de un vistazo. Es ideal para tener una perspectiva clara de tus próximos compromisos.',
      placement: 'right',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#weekly-calendar-main',
      title: 'Organiza tu tiempo',
      content: 'En esta vista puedes arrastrar tus tareas para asegurar que tus metas tengan el espacio que merecen en tu agenda.',
      placement: 'left',
      disableBeacon: true,
      spotlightClicks: true,
      spotlightPadding: 20,
      width: 288,
    } as Step,
    {
      target: '#nav-folders',
      title: 'Organiza por cuadernos',
      content: 'Haz clic aquí para gestionar tus cuadernos. Separar tus áreas de vida es clave para mantener el foco en lo que importa.',
      placement: 'right',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#folders-header',
      title: 'Tus espacios de enfoque',
      content: 'Este es tu centro de organización. Aquí divides tus grandes metas en cuadernos manejables como Trabajo, Salud o Proyectos Personales.',
      placement: 'bottom',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#btn-new-folder',
      title: 'Tus cuadernos de trabajo',
      content: 'Este botón es tu punto de partida. Úsalo para crear cuadernos dedicados a cada sueño o responsabilidad principal.',
      placement: 'bottom',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#nav-profile',
      title: 'Tu progreso',
      content: 'Desde aquí puedes acceder a tu perfil para ver estadísticas, rachas y logros desbloqueados.',
      placement: 'right',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#profile-stats-section',
      title: 'Monitorea tu crecimiento',
      content: 'Aquí verás tus rachas y éxitos totales. Mantener tu racha diaria es una forma simple de construir hábitos consistentes.',
      placement: 'bottom',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '#profile-weekly-report',
      title: 'Tu inteligencia semanal',
      content: 'Este reporte analiza tu eficiencia y te muestra cuánto tiempo y energía has ahorrado gracias a tu enfoque.',
      placement: 'top',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: 'body',
      title: 'Todo listo',
      content: 'Ya estás preparado para dominar tu día con Adonai. Empieza creando tu primera meta.',
      placement: 'center',
      disableBeacon: true,
      spotlightClicks: true,
    },
  ];

  return steps;
};
